---
micronaut:
  application:
    name: prueba-mongo

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
  options:
      maxConnectionIdleTime: 5000
      readConcern: majority
  cluster:
        maxWaitQueueSize: 5
  connectionPool:
        maxSize: 20

